### PR TITLE
Bump `stm32f4xx-hal` version to `0.10`

### PR DESCRIPTION
**Pull request by charlesincharge**
Updates the function calls according to the `stm32f4xx-hal` API changes.

### CODE REVIEW

**Comment by burrbull** [comment]
`stm32f4xx-hal` is already 0.17

**Comment by charlesincharge** [comment]
@burrbull I'm new to `stm32f4xx-hal` so I wanted to do the updates in this repo incrementally. Figured it would still help to slowly upgrade the `stm32f4xx-hal` dependency here. This will keep the PRs smaller and easier to review.

If you'd prefer me to just open a PR when I've done the full refactor to `stm32f4xx-hal=0.17`, let me know. Thanks!

**Comment by burrbull** [comment]
I'm merging this one, but I recommend you try to do all-in-one.

**Comment by charlesincharge** [comment]
Thanks @burrbull ! I'll try that for the next one.

**Pull request merged**
