### PR TITLE
add user button with example

### PR DESCRIPTION
**Pull request by finga**
Here is an example on how to use the button without interrupts.

I am just starting with embeded rust, so please advise if something can be improved.

### CODE REVIEW

**Comment by therealprof** [comment]
`Unwrap`s are rather expensive (because they bring in the panic and formatting machinery) and superfluous when operations cannot fail anyway. If you want to silence the "must use" warnings on unfailable operations you can use an anonymous let binding like `let _ = ...` or you can turn the `Result` into an `Option` by calling `ok()` on them.

Other than this nitpick your PR looks good to me.

**Comment by rotty** [comment]
@therealprof I don't think your reasoning against `unwrap` is valid in this case; since the `Infallible` type has no instances (i.e. it cannot be constructed), the compiler should be able to figure out that the panic branch is unreachable, and hence _not_ bring in the panic machinery for the `unwrap` calls in this case.

I'll try to provide playground links to either validate, or disproof my reasoning.

**Comment by rotty** [comment]
The `##rust` IRC channel on freenode was quick to come up with a very convincing confirmation of my reasoning, kindly providing this example:

```
pub fn foo(r: Result<i32, std::convert::Infallible>) -> i32 {
    r.unwrap()
}
```

With `-C opt-level=1` or higher (but not level 0), this gets compiled down to code not involving `unwrap` machinery, as evidenced by [this compiler explorer link](https://rust.godbolt.org/z/GeAW2R). Also it was pointed out that `std::mem::size_of::<Result<i32, std::convert::Infallible>>()` will evaluate to `4` even at opt-level 0, which leaves no place for a discriminant, so there can be no branching on the (non-existing) discriminant. At opt level 0, the compiler seems not to eliminate the must-be-dead code involving the panic machinery, which is not surprising, given that we asked for "no optimizations whatsoever".

I thus conclude that unwrapping a `Result<T, Infallible>` should be a safe pattern, even in an embedded context.

I would have been seriously surprised and disappointed if this would not be the case, as `Result<T, Infallible>` being performance-equivalent to `T` falls squarely into the "zero-cost" abstraction category that Rust takes pride in.

**Comment by therealprof** [comment]
> I thus conclude that unwrapping a Result<T, Infallible> should be a safe pattern, even in an embedded context.

Blind unwrapping is never a good/safe pattern irregardless of cost. You know it's infallible, a random reader does not and potentially has to find the panicing line in a sea of `unwrap`s.

> At opt level 0, the compiler seems not to eliminate the must-be-dead code involving the panic machinery, which is not surprising, given that we asked for "no optimizations whatsoever".

Right, it still is a problem. Any opt level higher than 0 is pretty much undebuggable so keeping the -O0 binary size down can be a make or break thing.

**Comment by rotty** [comment]
> > I thus conclude that unwrapping a Result<T, Infallible> should be a safe pattern, even in an embedded context.
> 
> Blind unwrapping is never a good/safe pattern irregardless of cost. You know it's infallible, a random reader does not and potentially has to find the panicing line in a sea of `unwrap`s.

It's not *blindly* unwapping, as you seem to indicate yourself. An `unwrap` in properly written library code should _never_ trigger, unless there's a bug. A comment may be in order, even more so if one would go with the `let _ = ...` pattern. The `unwrap()` basically a (quite minimal) form of that comment in code in my eyes.

> 
> > At opt level 0, the compiler seems not to eliminate the must-be-dead code involving the panic machinery, which is not surprising, given that we asked for "no optimizations whatsoever".
> 
> Right, it still is a problem. Any opt level higher than 0 is pretty much undebuggable so keeping the -O0 binary size down can be a make or break thing.

If you do not have the flash size available to bring in the formatting machinery on your target, you can use a panic handler that does not use that machinery, as described in the [embedded book chapter on panicking](https://rust-embedded.github.io/book/start/panicking.html).

**Comment by therealprof** [comment]
> The unwrap() basically is a (quite minimal) form of that comment in code in my eyes.

I prefer `.ok()` to indicate that this will either not fail or failure can be ignored.

> If you do not have the flash size available to bring in the formatting machinery on your target, you can use a panic handler that does not use that machinery, as described in the embedded book chapter on panicking.

May I suggest you familiarize yourself with the topic, e.g. by reading https://jamesmunns.com/blog/fmt-unreasonably-expensive/

On targets with small flash even a "light up a led when a button is pressed" easily fails to fit at -O0. No (explicit) formatting involved.

**Comment by rotty** [comment]
> > I thus conclude that unwrapping a Result<T, Infallible> should be a safe pattern, even in an embedded context.
> 
> Blind unwrapping is never a good/safe pattern irregardless of cost.
>
I've now re-read your comment, and I got a different possible meaning of what you mean by "blindly". If my (second) reading is correct, you are arguing that one should never use `unwrap()` in cases where you know it cannot fail, and instead explicitly ignore the result. I would still argue against that reasoning: you can only do that in cases where you do not need the inner value, so if the `Result<T, Infallible>` pattern is supposed to make sense in the embedded context, you _need_ to `unwrap()`, if you care about the inner `T`. Since this pattern is employed by the `embedd-hal` crate for "interesting" values of `T`, I would argue by using `let _ = ...` in that case, you are providing an optimization that will become moot as soon as the application uses any HAL method that it needs the inner value of. I would further argue that since non-toy applications are going to have to deal with the code-size issue in any case, going with `let _ = ...` buys you not much in practice, at the cost of writing what seems to me quite unidiomatic code.

Maybe that is the crux of this argument; for me `let _ =  ...` for `Result` values reads as "I don't care about errors here" (which should raise all kinds of red flags for the reader), while `unwrap` reads as "I know the error cannot happen". I hence maintain the *idiomatic* thing to do is the `unwrap()`.

> You know it's infallible, a random reader does not and potentially has to find the panicing line in a sea of `unwrap`s.
>
I don't follow. With the formatting machinery available, the reader will not have to guess at all, since there will be a backtrace indicating the panicking code site. With the `panic-abort` panic handler, you should be able to use a debugger.

**Comment by rotty** [comment]
> May I suggest you familiarize yourself with the topic, e.g. by reading https://jamesmunns.com/blog/fmt-unreasonably-expensive/
> 
> On targets with small flash even a "light up a led when a button is pressed" easily fails to fit at -O0. No (explicit) formatting involved.

**Comment by therealprof** [comment]
> I don't follow. With the formatting machinery available, the reader will not have to guess at all, since there will be a backtrace indicating the panicking code site. With the panic-abort panic handler, you should be able to use a debugger.

How much real life experience do you actually have with embedded Rust?

Your arguments seem to be mostly real world experience defying handwavery... Stack traces are broken and until the recently introduced caller tracking you wouldn't get any useful info unless you provided an explicit panic message, e.g. by using `expect`.

But again that point is moot if the binary doesn't even link due to not fitting into flash.

**Comment by rotty** [comment]
> > The unwrap() basically is a (quite minimal) form of that comment in code in my eyes.
> 
> I prefer `.ok()` to indicate that this will either not fail or failure can be ignored.
>
This is the thing I take issue with: `unwrap()` is more explicit, as it clearly indicates the former, while (at least in non-embedded Rust), `.ok()` always indicates the latter.

> > If you do not have the flash size available to bring in the formatting machinery on your target, you can use a panic handler that does not use that machinery, as described in the embedded book chapter on panicking.
> 
> May I suggest you familiarize yourself with the topic, e.g. by reading https://jamesmunns.com/blog/fmt-unreasonably-expensive/
>
> On targets with small flash even a "light up a led when a button is pressed" easily fails to fit at -O0. No (explicit) formatting involved.
>
I have read that (very recommendable) blog post a while ago, and skimmed it again now, to make sure I'm not missing anything. I'm still not convinced that it applies to `Result<T, Infallible>`, as my impression is that the design of the `embedded-hal` is such that `unwrap` on these kinds of `Result` is bound to be inevitable, and as such not worth avoiding. It would be interesting to know about @japaric's option on this, and see the binary size implications (as in the linked blog post) when the error type is `Infallible`.

**Comment by therealprof** [comment]
> see the binary size implications (as in the linked blog post) when the error type is Infallible.

As you've noted yourself on -O0 nothing is compiled out. Which is also the reason that even a simple compiler_fence is rather expensive, cf. https://github.com/rust-lang/rust/issues/68208

You're free to do the measurement yourself and show me some convincing numbers. Until then I don't want to see `unwrap` in example code in my crate.

**Comment by rotty** [comment]
> > I don't follow. With the formatting machinery available, the reader will not have to guess at all, since there will be a backtrace indicating the panicking code site. With the panic-abort panic handler, you should be able to use a debugger.
> 
> How much real life experience do you actually have with embedded Rust?
> 
As I wrote in [my PR](#2) to this crate, my experience is basically zero.

> Your arguments seem to be mostly real world experience defying handwavery... Stack traces are broken and until the recently introduced caller tracking you wouldn't get any useful info unless you provided an explicit panic message, e.g. by using `expect`.
>
Ok, I was not aware that stack traces are broken on embedded (see above). That panic backtraces are not giving useful info before the caller tracking improvement is just not in my (non-embedded experience) -- they are very unhelpful, but after looking at the mess of lines for a few seconds, you can locate the panic location easily.
  
Anyhow, I'll leave this be now -- I realize I have taken this issue hostage for a discussion about what idiomatic embededded Rust should look like, going only from my experience as a non-embedded Rust programmer, and upon making (IMHO, still reasonable) assumptions about the design of `embedded-hal` and how it relates to `unwrap()` in dependent crates.

This is your crate, and if you say its better to use the `let _ = ...` pattern instead of `unwrap()`, I trust you based on your experience in actually doing embedded Rust, instead of just arm-chair-philosophizing about it, like I am. I just wanted to point out that the `Infallible` type may be special here, and might slant the considerations such that `unwrap` becomes a reasonable thing to do, even in an embedded context.

**Comment by therealprof** [comment]
> This is your crate, and if you say its better to use the let _ = ... pattern instead of unwrap(), 

No, I said I prefer `.ok()`.

> I just wanted to point out that the Infallible type may be special here, and might slant the considerations such that unwrap becomes a reasonable thing to do, even in an embedded context.

I'm very well aware of the `Infallible` type and what it does for optimized code. For unoptimized code it's bad though, especially when you know it cannot happen.

At the same time `unwrap` is pretty much always a bad idea, if needs be use `expect` instead and tell why the application is supposed to be crashing and burning at this point instead of letting the user figure out the reason for the panic by themselves...

**Comment by rotty** [comment]
> At the same time `unwrap` is pretty much always a bad idea, if needs be use `expect` instead and tell why the application is supposed to be crashing and burning at this point instead of letting the user figure out the reason for the panic by themselves...

Are you talking about `unwrap` being a bad thing in general, or about the embedded case specifically? As a statement that Rust code in general, regardless of the context, should never use `unwrap()`, I disagree, but that (in my mind) is a matter of style and very context-specific. Reasonable people can have different opinions on this. However, this is now _really_ off-topic.

**Comment by finga** [comment]
Does that also imply that I cannot use the iterator here?
Could you give an advise on how to handle this elegantly?

**Comment by therealprof** [comment]
Not quite sure what you're trying to do with the iterator here to be honest, but if you want simplify this a bit and get rid of the `unwraps` you could replace the `loop` with a `for` loop or a `for_each` call on the iterator.

**Comment by therealprof** [comment]
@finga So you don't want the example included?

**Comment by finga** [comment]
@therealprof Tbh I do not care, I only wanted to get into something new where I could maybe also contribute and help out.
It seems to me, that the embedded-rust community has not yet decided on how to deal with the discussed topics. If that is wrong, still, I could not find much if any documentation, etc. about it. That is why I decided to work on something else.

**Comment by therealprof** [comment]
Well, I happen to be the owner and sole maintainer of this repository and I'd very much like to see more examples and contributions. Your example is very much appreciated here and I'd be happy to help you out with this and other topics.

I'm sorry for not shutting down this fruitless side discussion, I can see why this is distracting and frustrating for you.

**Comment by finga** [comment]
My decision stays the same, I am not interested in spending any more time on this.
I want to express again, that my decision does not relate to this discussion. Further, I did not receive this discussion as distraction at all as I got some new insights.

The reasons are, as already mentioned, that it seems to me that the fundament of embedded-rust is not yet completely clear as well as the documentation.

**Pull request closed without merging**
